version: '4.35'

services:
  app:
    image: dockertest:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    container_name: postgres_container
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d